# Generated by Django 5.1.7 on 2025-05-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
